#!/bin/sh
set -eu

APP_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
. "$APP_DIR/scripts/ios-process-guard.sh"
. "$APP_DIR/scripts/ios-pods-ensure.sh"
REPO_ROOT=$(CDPATH= cd -- "$APP_DIR/../.." && pwd)
IOS_DIR="$APP_DIR/ios"
DERIVED_DATA_PATH=${SOLID_NATIVE_IOS_DERIVED_DATA:-"$IOS_DIR/build/device-tests"}
BUNDLE_IDENTIFIER=${SOLID_NATIVE_IOS_BUNDLE_ID:-dev.solidnative.e2e}
RESULTS_DIRECTORY="$DERIVED_DATA_PATH/Logs/Test"
RESULT_BUNDLE_PATH="$RESULTS_DIRECTORY/SolidNativeE2E-$(date +%Y%m%d-%H%M%S).xcresult"
DIAGNOSTICS_PARENT=

cleanup() {
  stop_solid_native_ios_process_guard
  if [ -n "$DIAGNOSTICS_PARENT" ]; then
    rm -rf "$DIAGNOSTICS_PARENT"
  fi
}

: "${SOLID_NATIVE_IOS_DESTINATION:?Set SOLID_NATIVE_IOS_DESTINATION to the connected device identifier shown by xcrun xctrace list devices.}"
: "${SOLID_NATIVE_IOS_TEAM:?Set SOLID_NATIVE_IOS_TEAM to the Apple Development team identifier selected in Xcode.}"
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

node "$APP_DIR/scripts/ios-stop-processes.mjs" "$SOLID_NATIVE_IOS_DESTINATION"
node "$APP_DIR/scripts/ios-device-preflight.mjs" "$SOLID_NATIVE_IOS_DESTINATION"
node "$APP_DIR/scripts/ios-host-preflight.mjs"
pnpm --dir "$REPO_ROOT" --filter '@solid-native/native-e2e...' build
ensure_solid_native_ios_pods
mkdir -p "$RESULTS_DIRECTORY"

start_solid_native_ios_process_guard
set +e
xcodebuild \
  -workspace "$IOS_DIR/SolidNativeE2E.xcworkspace" \
  -scheme SolidNativeE2E \
  -configuration Release \
  -destination "id=$SOLID_NATIVE_IOS_DESTINATION" \
  -derivedDataPath "$DERIVED_DATA_PATH" \
  DEVELOPMENT_TEAM="$SOLID_NATIVE_IOS_TEAM" \
  CODE_SIGN_STYLE=Automatic \
  SOLID_NATIVE_APP_BUNDLE_ID="$BUNDLE_IDENTIFIER" \
  -allowProvisioningUpdates \
  -collect-test-diagnostics never \
  -resultBundlePath "$RESULT_BUNDLE_PATH" \
  -only-testing:SolidNativeE2EUITests/SolidNativeE2EUITests/testAppStateEventDeliveryOnPhysicalDevice \
  test
XCODEBUILD_STATUS=$?
set -e
if [ "$XCODEBUILD_STATUS" -ne 0 ]; then
  node "$APP_DIR/scripts/ios-xctest-failure-hint.mjs" "$RESULT_BUNDLE_PATH" || true
  exit "$XCODEBUILD_STATUS"
fi

DIAGNOSTICS_PARENT=$(mktemp -d "${TMPDIR:-/tmp}/solid-native-ios-test.XXXXXX")
DIAGNOSTICS_DIRECTORY="$DIAGNOSTICS_PARENT/diagnostics"
xcrun xcresulttool export diagnostics \
  --path "$RESULT_BUNDLE_PATH" \
  --output-path "$DIAGNOSTICS_DIRECTORY"

for marker in \
  SOLID_NATIVE_TURBOMODULE_SUCCEEDED \
  SOLID_NATIVE_GENERATED_TURBOMODULE_SCHEMA_SUCCEEDED \
  SOLID_NATIVE_GENERATED_TURBOMODULE_SUCCEEDED \
  SOLID_NATIVE_TURBOMODULE_ASYNC_SUCCEEDED \
  SOLID_NATIVE_STORAGE_MODULE_SUCCEEDED \
  SOLID_NATIVE_NOTIFICATION_DELIVERY_SUCCEEDED \
  SOLID_NATIVE_NOTIFICATION_CAUSALITY_SUCCEEDED \
  SOLID_NATIVE_CAMERA_PERMISSION_SUCCEEDED \
  SOLID_NATIVE_CAMERA_DEVICES_SUCCEEDED \
  SOLID_NATIVE_CAMERA_PREVIEW_SUCCEEDED \
  SOLID_NATIVE_CAMERA_PREVIEW_CAUSALITY_SUCCEEDED \
  SOLID_NATIVE_APP_STATE_CAUSALITY_SUCCEEDED \
  SOLID_NATIVE_CAMERA_CAPTURE_SUCCEEDED \
  SOLID_NATIVE_CAMERA_CAPTURE_CAUSALITY_SUCCEEDED \
  SOLID_NATIVE_CAUSAL_SCOPE_SUCCEEDED \
  SOLID_NATIVE_CAUSAL_OWNER_SUCCEEDED \
  SOLID_NATIVE_CAUSAL_COMPUTATION_SUCCEEDED \
  SOLID_NATIVE_RUNTIME_RESOURCE_SUCCEEDED \
  SOLID_NATIVE_CAMERA_SESSION_SUCCEEDED \
  SOLID_NATIVE_COLD_START_DEEP_LINK_SUCCEEDED \
  SOLID_NATIVE_COLD_START_RESET_SUCCEEDED \
  SOLID_NATIVE_TURBOMODULE_EVENT_SUCCEEDED \
  SOLID_NATIVE_CODEGEN_COMPONENT_SUCCEEDED \
  SOLID_NATIVE_MOUNT_LIFECYCLE_SUCCEEDED \
  SOLID_NATIVE_FRAME_SUCCEEDED \
  SOLID_NATIVE_E2E_READY \
  SOLID_NATIVE_JSI-EVENT-UPDATE-SUCCEEDED \
  SOLID_NATIVE_SOLID_SIGNAL_SUCCEEDED \
  SOLID_NATIVE_MEASUREMENT_SUCCEEDED \
  SOLID_NATIVE_ASYNC_BOUNDARY_SUCCEEDED \
  SOLID_NATIVE_SCROLL_COMMAND_SUCCEEDED \
  SOLID_NATIVE_SCROLL_EVENT_SUCCEEDED \
  SOLID_NATIVE_IMAGE_LOAD_SUCCEEDED \
  SOLID_NATIVE_ACTIVITY_INDICATOR_SUCCEEDED \
  SOLID_NATIVE_SCROLL_IMAGE_CAUSALITY_SUCCEEDED \
  SOLID_NATIVE_SCROLLVIEW_SUCCEEDED \
  SOLID_NATIVE_NAVIGATION_PUSH_SUCCEEDED \
  SOLID_NATIVE_NAVIGATION_BACK_EVENT_SUCCEEDED \
  SOLID_NATIVE_NAVIGATION_BACK_CAUSALITY_SUCCEEDED \
  SOLID_NATIVE_NAVIGATION_POP_SUCCEEDED \
  SOLID_NATIVE_NAVIGATION_FOCUS_SUCCEEDED \
  SOLID_NATIVE_NAVIGATION_FOCUS_SCOPE_SUCCEEDED \
  SOLID_NATIVE_NAVIGATION_PERSISTENCE_SUCCEEDED \
  SOLID_NATIVE_NOTIFICATION_CANCEL_SUCCEEDED \
  SOLID_NATIVE_CAMERA_SESSION_STOP_SUCCEEDED \
  SOLID_NATIVE_DEEP_LINK_EVENT_SUCCEEDED \
  SOLID_NATIVE_DEEP_LINK_CAUSALITY_SUCCEEDED \
  SOLID_NATIVE_DEEP_LINK_MOUNT_SUCCEEDED \
  SOLID_NATIVE_TEXTINPUT_SUCCEEDED \
  SOLID_NATIVE_TEXTINPUT_MULTILINE_SUCCEEDED \
  SOLID_NATIVE_SWITCH_SUCCEEDED \
  SOLID_NATIVE_MODAL_SHOW_SUCCEEDED \
  SOLID_NATIVE_MODAL_DISMISS_SUCCEEDED \
  SOLID_NATIVE_TEXTINPUT_SELECTION_SUCCEEDED \
  SOLID_NATIVE_TEXTINPUT_SUBMIT_SUCCEEDED \
  SOLID_NATIVE_KEYBOARD_STATE_SUCCEEDED \
  SOLID_NATIVE_IDENTITY_RECLAMATION_SUCCEEDED \
  SOLID_NATIVE_TEARDOWN_SUCCEEDED
do
  if ! grep -R -F -q "$marker" "$DIAGNOSTICS_DIRECTORY"; then
    echo "Missing iOS physical-device proof marker: $marker" >&2
    exit 1
  fi
done

echo "Verified the complete Solid Native iOS physical-device markers."
