import { REACT_NATIVE_0_87_RELEASE } from "@solid-native/react-native-compat";

export const SOLID_NATIVE_CLI_VERSION = "0.0.0";
export const VERIFIED_REACT_NATIVE_PACKAGE_VERSION =
  REACT_NATIVE_0_87_RELEASE.packageVersion;
export const VERIFIED_REACT_NATIVE_RUNTIME_VERSION =
  REACT_NATIVE_0_87_RELEASE.runtimeVersion;
/** @deprecated Prefer VERIFIED_REACT_NATIVE_PACKAGE_VERSION for clarity. */
export const VERIFIED_REACT_NATIVE_VERSION =
  VERIFIED_REACT_NATIVE_PACKAGE_VERSION;
export const VERIFIED_SAFE_AREA_CONTEXT_VERSION = "5.8.1";
export const VERIFIED_REACT_NATIVE_SCREENS_VERSION = "4.27.0";
export const VERIFIED_SOLID_VERSION = "2.0.0-rc.3";
export const VERIFIED_HERMES_COMPILER_VERSION =
  REACT_NATIVE_0_87_RELEASE.hermesCompilerVersion;
export const VERIFIED_HERMES_BYTECODE_VERSION =
  REACT_NATIVE_0_87_RELEASE.hermesBytecodeVersion;
